#!/bin/bash
set -e

# Set the environment variables for the users and passwords
POSTGRES_USER=${POSTGRES_USER:-postgres}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
RPE_DATABASE=${RPE_DATABASE:-rpe_db}
RPE_ADMIN_USER=${RPE_ADMIN_USER:-rpe_admin}
RPE_ADMIN_PASSWORD=${RPE_ADMIN_PASSWORD:-admin_password}
RPE_BACKEND_USER=${RPE_BACKEND_USER:-rpe_backend}
RPE_BACKEND_PASSWORD=${RPE_BACKEND_PASSWORD:-backend_password}

# Execute the SQL commands
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE ${RPE_DATABASE};
    \connect ${RPE_DATABASE};

    CREATE USER ${RPE_ADMIN_USER} WITH PASSWORD '${RPE_ADMIN_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${RPE_DATABASE} TO ${RPE_ADMIN_USER};

    CREATE USER ${RPE_BACKEND_USER} WITH PASSWORD '${RPE_BACKEND_PASSWORD}';
    GRANT CONNECT ON DATABASE ${RPE_DATABASE} TO ${RPE_BACKEND_USER};
    GRANT USAGE ON SCHEMA public TO ${RPE_BACKEND_USER};
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${RPE_BACKEND_USER};
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${RPE_BACKEND_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${RPE_BACKEND_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO ${RPE_BACKEND_USER};
    GRANT ALL PRIVILEGES ON SCHEMA public TO ${RPE_BACKEND_USER};
EOSQL
